laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('dashboard/users', \App\Http\Controllers\UserController::class)->middleware('auth');

Route::resource('dashboard/company', \App\Http\Controllers\CompanyController::class)->middleware('auth');

laravel/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="grid grid-cols-1 ">

            @auth
                <a href="{{ route('users.index') }}"
                   class=" mt-8 bg-white dark:bg-gray-800 overflow-hidden shadow sm:rounded-lg text-lg text-gray-700">

                    <div class="p-6">
                        <div class="flex items-center">
                            Users
                        </div>

                    </div>

                </a>
                <a href="{{ route('company.index') }}"
                   class=" mt-2 bg-white dark:bg-gray-800 overflow-hidden shadow sm:rounded-lg text-lg text-gray-700">

                    <div class="p-6">
                        <div class="flex items-center">
                            Company
                        </div>

                    </div>

                </a>
            @endif

        </div>
    </div>
</x-app-layout>